import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';

@Component({
  selector: 'app-ai-draft-badge',
  standalone: true,
  imports: [MatIconModule, MatTooltipModule],
  template: `
    <span class="ai-badge"
      [matTooltip]="tooltip || 'This content was generated by AI and can be edited'">
      <mat-icon>auto_awesome</mat-icon>
      AI-generated
    </span>
  `,
  styles: [`
    .ai-badge {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      padding: 2px 8px;
      border-radius: 12px;
      background: var(--mat-sys-primary-container, #e3f2fd);
      color: var(--mat-sys-on-primary-container, #1565c0);
      font-size: 11px;
      font-weight: 500;
      white-space: nowrap;
      vertical-align: middle;

      mat-icon {
        font-size: 14px;
        width: 14px;
        height: 14px;
      }
    }
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AiDraftBadge {
  @Input() tooltip?: string;
}
