#!/usr/bin/env node
/**
 * ingest-tokens.mjs — compile ngx-library's SCSS theme into flat, portable CSS for this app.
 *
 * WHY THIS EXISTS
 * ---------------
 * This app mirrors the ZeroBias portal's look. Before this script, `src/styles/_tokens.scss`
 * was ~111 lines of HAND-TRANSCRIBED values — correct only for as long as someone kept
 * retyping them correctly, and silently wrong the moment the portal moved. This script
 * replaces transcription with compilation: it reads ngx-library out of node_modules and
 * compiles its theme exactly the way ngx-library's own component-showcase does
 * (mirroring that app's `src/styles.scss`), so the emitted values are identical to the
 * portal's BY CONSTRUCTION.
 *
 *     html { color-scheme: light; @include mat.theme(theme.$theme); }
 *     @include zb-theme-variables-light(theme.$theme);   // -> html { --zb-* }
 *     @include zb-theme-variables-dark(theme.$altTheme);  // -> body.dark-theme { --zb-* }
 *
 * ngx-library is a VALUES SOURCE, never a runtime dependency — this app builds its own React
 * components and imports no Angular code. Angular Material is likewise BUILD-TIME ONLY: it is
 * what resolves the M3 layer (`mat.theme()`) that the `--zb-*` tokens reference. Nothing
 * Angular ships in the bundle; the output is plain CSS custom properties.
 *
 * ngx-library publishes no `exports` entry for its styles, so deep-importing
 * `node_modules/@zerobias-org/ngx-library/src/styles/` is the only way in. That is expected,
 * not a workaround.
 *
 * Re-run after any ngx-library bump:  npm run ingest:tokens
 */
import * as sass from 'sass';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const NGX = resolve(ROOT, 'node_modules/@zerobias-org/ngx-library');
const NGX_STYLES = resolve(NGX, 'src/styles');
const OUT_DIR = resolve(ROOT, 'src/styles');
const OUT_TOKENS = resolve(OUT_DIR, '_tokens.generated.scss');
const OUT_BREAKPOINTS = resolve(OUT_DIR, '_breakpoints.generated.scss');

const ngxVersion = JSON.parse(readFileSync(resolve(NGX, 'package.json'), 'utf8')).version;

// Mirrors ngx-library's component-showcase styles.scss. `zb-theme-variables-light` internally
// applies `mat.theme-overrides()` with literal hex, so the --mat-sys-* vars that the --zb-*
// tokens reference are concretely defined in the same output.
const entry = `
@use '@angular/material' as mat;
@use 'theme' as theme;
@use 'theme-variables' as *;

html {
  color-scheme: light;
  @include mat.theme(theme.$theme);
}

@include zb-theme-variables-light(theme.$theme);
@include zb-theme-variables-dark(theme.$altTheme);
`;

console.log(`Ingesting tokens from @zerobias-org/ngx-library@${ngxVersion}`);

const result = sass.compileString(entry, {
  loadPaths: [NGX_STYLES, resolve(ROOT, 'node_modules')],
  style: 'expanded',
  silenceDeprecations: ['mixed-decls', 'import', 'global-builtin', 'color-functions'],
});

// --- Guard: no --zb-* reference may dangle ----------------------------------------------
// This is the whole reason to trust the output. A --zb-* token that resolves to
// var(--mat-sys-X) is only portable if --mat-sys-X is itself DEFINED in this file. If
// Material's theme emission ever stops covering one, the token silently resolves to nothing
// and the component renders unstyled — a failure that looks like a CSS typo and costs hours.
// Fail the build instead of shipping it.
const css = result.css;
const defined = new Set([...css.matchAll(/^\s*(--[\w-]+)\s*:/gm)].map((m) => m[1]));
const referenced = new Set([...css.matchAll(/var\(\s*(--[\w-]+)/g)].map((m) => m[1]));
const dangling = [...referenced].filter((v) => !defined.has(v)).sort();

if (dangling.length) {
  console.error(`\nERROR: ${dangling.length} custom propert${dangling.length === 1 ? 'y' : 'ies'} referenced but never defined:`);
  for (const v of dangling) console.error(`  ${v}`);
  console.error('\nThe token layer is not self-contained. Do not ship it.');
  process.exit(1);
}

const zbCount = [...defined].filter((v) => v.startsWith('--zb-')).length;
const matCount = [...defined].filter((v) => v.startsWith('--mat-')).length;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  OUT_TOKENS,
  `// GENERATED by scripts/ingest-tokens.mjs — DO NOT EDIT.
//
// Source: @zerobias-org/ngx-library@${ngxVersion}, compiled with Angular Material (build-time only).
// Re-run \`npm run ingest:tokens\` after any ngx-library bump.
//
// ${zbCount} --zb-* tokens over ${matCount} --mat-sys-* values they resolve through.
// Light on \`html\`; dark on \`body.dark-theme\` — the theme contract this app implements in
// src/lib/theme.ts and shares with the portal.
// Verified self-contained: every var() reference resolves within this file.

${css}
`,
);

// --- Breakpoints -------------------------------------------------------------------------
// Copied verbatim so our SCSS can use the SAME breakpoints as the portal. These live ONLY in
// ngx-library's mixins — there is no token for them — so without this copy our responsive
// behavior would diverge silently at every viewport but desktop, with colors and spacing
// still looking perfect. They must actually be USED, not merely vendored.
const mq = readFileSync(resolve(NGX_STYLES, 'mediaQueries.scss'), 'utf8');
writeFileSync(
  OUT_BREAKPOINTS,
  `// GENERATED by scripts/ingest-tokens.mjs — DO NOT EDIT.
// Verbatim from @zerobias-org/ngx-library@${ngxVersion} src/styles/mediaQueries.scss.
// All breakpoints are max-width (desktop-first), matching the portal exactly.

${mq}`,
);

const breakpoints = [...mq.matchAll(/max-width:\s*(\d+)px/g)].map((m) => m[1]);

console.log(`  src/styles/_tokens.generated.scss`);
console.log(`    ${zbCount} --zb-* tokens, ${matCount} --mat-* values, 0 dangling refs`);
console.log(`  src/styles/_breakpoints.generated.scss`);
console.log(`    ${breakpoints.length} breakpoints: ${breakpoints.join(', ')}`);
