import type { Metadata } from "next";
import { Roboto, Montserrat } from "next/font/google";
import { CurrentUserProvider } from "@/context/CurrentUserContext";
import "./globals.css";
import "../styles/styles.scss";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" type="image/png" href="/favicon.png"></link>
      <body>
          <CurrentUserProvider>{children}</CurrentUserProvider>
      </body>
    </html>
  );
}
