// AUTO-GENERATED by scripts/gen-neon-env.mjs — DO NOT COMMIT
// Regenerated on every `npm start` from NEON_DATABASE_URL in .env.local
export const NEON_DATABASE_URL = 'postgresql://neondb_owner:npg_NjsYRTy2U6re@ep-aged-fog-af9wu771-pooler.c-2.us-west-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require';
